name = "Barebones Bilberry Hugo Theme"
license = "MIT"
licenselink = "https://github.com/marian42/bilberry-hugo-theme"
description = "Barebones Bilberry is a simple hugo theme with few features. It is an adaption and simplification of the Bilberry Hugo Theme by Lednerb."
homepage = "https://github.com/marian42/bilberry-hugo-theme"
tags = ["blog", "personal", "responsive", "font awesome", "pages", "posts", "highlight.js", "syntax highlighting"]
features = []
min_version = "0.46"

theme_version = "1.0.0"

[author]
  name = "Lednerb | Sascha Brendel"
  homepage = "https://sascha-brendel.de"

[original]
  name = "Lednerb | Sascha Brendel"
  homepage = "https://sascha-brendel.de"
  repo = "https://github.com/Lednerb/bilberry-hugo-theme"
